"""Regenerate the self-contained Finder-friendly combat demo."""
from pathlib import Path
import base64
import re
folder = Path(__file__).resolve().parent
html = (folder / 'index.template.html').read_text()
styles = ['../../dice/dice.css', 'encounter.css']
scripts = ['../../dice/dice.js', '../../stats/stats.js', 'combat.js', 'encounter.js']
html = html.replace('<!-- STYLES -->', '\n'.join('<style>\n'+(folder / src).read_text()+'\n</style>' for src in styles))
html = html.replace('<!-- SCRIPTS -->', '\n'.join('<script>\n'+(folder / src).read_text().replace('</script', '<\\/script')+'\n</script>' for src in scripts))
html = re.sub(r'src="([^"]+\.png)"', lambda match: 'src="data:image/png;base64,'+base64.b64encode((folder / match[1]).read_bytes()).decode()+'"', html)
html = html.replace('<!doctype html>', '<!doctype html>\n<!-- Generated by build-demo.py. Edit the separate sources and rebuild. -->', 1)
(folder / 'index.html').write_text(html)
print('Built combat/encounter/index.html')
