"""Build the Finder-friendly demo from the separate HTML, CSS and JS sources."""
from pathlib import Path

folder = Path(__file__).resolve().parent
html = (folder / "index.template.html").read_text()
for source in ("../dice/dice.css", "stats.css"):
    css = (folder / source).read_text()
    html = html.replace(f'<link rel="stylesheet" href="{source}">',
                        f'<style>\n/* Source: {source} */\n{css}\n</style>')
scripts = []
for source in ("../dice/dice.js", "stats.js", "stats-ui.js", "stats-demo.js"):
    html = html.replace(f'  <script src="{source}" defer></script>\n', "")
    js = (folder / source).read_text().replace("</script", "<\\/script")
    scripts.append(f'<script>\n/* Source: {source} */\n{js}\n</script>')
html = html.replace("</body>", "\n".join(scripts) + "\n</body>")
html = html.replace("<!doctype html>", "<!doctype html>\n<!-- Generated by build-demo.py; edit the separate source files, then rebuild. -->", 1)
(folder / "index.html").write_text(html)
print("Built self-contained stats/index.html")
